language: c

install: true

branches:
  only:
    - master
    - alan/example_api

script:
    - make clean 
    - make 
    - make -C tests/trie_tests
    - tests/trie_tests/test-trie
    - make -C tests/zset_tests
    - tests/zset_tests/test-zset
