language: c

install: true

branches:
  only:
    - master
    - alan/example_api

script:
    - make clean 
    - make 
    - make tests
    - ./tests/trie_tests/test-trie
    - ./tests/zset_tests/zset-trie
    - make clean
